services:
  - type: web
    name: wanderease-api
    env: python
    buildCommand: pip install --upgrade pip && pip uninstall -y bson && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0